### ISSUE TITLE
can not start ws_server error

### ISSUE THREAD

**Issue by Arsalan0098** [Itokoyamato/TokoVOIP_TS3#183]
hello i try to start it but 
```
   start ws_server
Running build tasks on resource ws_server - it'll restart once completed. Couldn't start resource ws_server. yarn install v1.21.0 info No lockfile found. warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json. [1/4] Resolving packages... Building resource ws_server failed. Error data: yarn failed!
```
and in the yarn-error.log file
```Arguments: 
  C:\FXServer\server\FXServer.exe C:\FXServer\server-data\resources\[system]\[builders]\yarn\yarn_cli.js install --ignore-scripts

PATH: 
  C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\npm

Yarn version: 
  1.21.0

Node version: 
  12.13.0

Platform: 
  win32 x64

Trace: 
  Error: write EIO
      at afterWriteDispatched (internal/stream_base_commons.js:150:25)
      at writeGeneric (internal/stream_base_commons.js:141:3)
      at WriteStream.Socket._writeGeneric (net.js:770:11)
      at WriteStream.Socket._write (net.js:782:8)
      at doWrite (_stream_writable.js:431:12)
      at writeOrBuffer (_stream_writable.js:415:5)
      at WriteStream.Writable.write (_stream_writable.js:305:11)
      at writeOnNthLine (C:\FXServer\server-data\resources\[system]\[builders]\yarn\yarn_cli.js:50236:12)
      at Spinner.render (C:\FXServer\server-data\resources\[system]\[builders]\yarn\yarn_cli.js:104491:48)
      at Spinner.start (C:\FXServer\server-data\resources\[system]\[builders]\yarn\yarn_cli.js:104481:10)

npm manifest: 
  {
    "name": "ws_server",
    "version": "1.5.4",
    "description": "",
    "main": "index.js",
    "scripts": {
      "start": "node index.js",
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "Itokoyamato",
    "license": "ISC",
    "dependencies": {
      "axios": "^0.19.2",
      "chalk": "^4.1.0",
      "console-stamp": "^0.2.9",
      "express": "^4.17.1",
      "lodash": "^4.17.19",
      "public-ip": "^4.0.1",
      "socket.io": "^2.3.0"
    },
    "devDependencies": {
      "nodemon": "^2.0.4"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
```
can you help please?

**Comment by Nightwalkersfear** [comment]
Same problem here.
